default: true

# Exclusions for deliberate/widespread violations
MD002: false     # First header should be a h1 header
MD013: false     # Line length
MD024: false     # Multiple headers with the same content
MD026: false     # Trailing punctuation in header
MD028: false     # Blank line inside blockquote (docusaurus is treating them as seperate blockquotes)
MD033: false     # Allow inline HTML
MD041: false     # First line in file should be a top level header
