language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
script:
  - yarn test
after_success:
  - yarn run semantic-release
branches:
  only:
    - master
