project_identifier_env: CROWDIN_DOCUSAURUS_PROJECT_ID
api_key_env: CROWDIN_DOCUSAURUS_API_KEY
base_path: "./"
preserve_hierarchy: true

files:
  -
    source: '/docs/**/*.md'
    translation: '/website/translated_docs/%locale%/**/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'es-ES': 'es-ES'
        'fr': 'fr'
        'ko': 'ko'
        'pt-BR': 'pt-BR'
        'zh-CN': 'zh-CN'
        'id': 'id'
        'de': 'de'
        'pl': 'pl'
        'ru': 'ru'
        'ja': 'ja'
        'nl': 'nl'
        'ro': 'ro'
        'in': 'in'

  -
    source: '/website/i18n/en.json'
    translation: '/website/i18n/%locale%.json'
    languages_mapping: *anchor
