

name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:[![Lint](https://github.com/all-contributors/all-contributors/actions/workflows/lint.yml/badge.svg?branch=master)](https://github.com/all-contributors/all-contributors/actions/workflows/lint.yml)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npx --package markdownlint-cli markdownlint **/*.md --ignore node_modules
