name: Offline link check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: lycheeverse/lychee-action@v2
        with:
          # Only check local files, no network requests
          args: --config './lychee.toml' --no-progress --offline --root-dir "$GITHUB_WORKSPACE/public/" 'src/content/docs/**/*.md'
          # Fail job when lychee returns a non-zero exit code
          fail: true
